# Generated by Django 5.2 on 2025-04-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='itinerarie',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
    ]
